{
  # GENERATED by RFC-0005 nix_provisioner from the task contract environment
  # manifest. Committed as a deliverable so build (AIFactory) and verify
  # (TFactory) share one flake.lock and cannot drift. Edit the manifest, not this.
  description = "Factory per-task toolchain (RFC-0005 Tier A)";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/567a49d1913ce81ac6e9582e3553dd90a955875f";
  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
      fontsConf = pkgs.makeFontsConf { fontDirectories = [ pkgs.dejavu_fonts ]; };
    in {
      devShells.${system}.default = pkgs.mkShell {
        packages = [
          pkgs.nodejs_22
          pkgs.playwright-test
          pkgs.dejavu_fonts
        ];
        # Nix-provided, version-matched browsers — no network download.
        PLAYWRIGHT_BROWSERS_PATH = "${pkgs.playwright-driver.browsers}";
        PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS = "true";
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1";
        # Headless chromium needs fontconfig to find a font, else text won't render.
        FONTCONFIG_FILE = fontsConf;
      };
    };
}

