#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Add src/app/helpers/wordcount.py

set -e

echo "========================================"
echo "Setting up Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check Python version
echo "Checking Python version..."
PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
echo -e "${GREEN}Python ${PYTHON_VERSION} found${NC}"

# Install dependencies with test extras
echo ""
echo "Installing project dependencies..."
pip install -e ".[test]" > /dev/null 2>&1 || {
    echo -e "${RED}Failed to install dependencies${NC}"
    exit 1
}
echo -e "${GREEN}Dependencies installed${NC}"

# Verify test environment
echo ""
echo "Verifying pytest installation..."
python -m pytest --version > /dev/null 2>&1 || {
    echo -e "${RED}pytest not available${NC}"
    exit 1
}
echo -e "${GREEN}pytest ready${NC}"

# Run existing tests to verify setup
echo ""
echo "Running existing tests to verify environment..."
python -m pytest tests/test_root.py -v 2>&1 || {
    echo -e "${YELLOW}Warning: Existing tests did not pass${NC}"
}

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Next steps:"
echo "1. Run: pytest tests/test_wordcount.py -v"
echo "2. Run: python -m pytest tests/ -v"
echo "3. Run: pip install -e . && uvicorn src.app.main:app --reload"
echo ""
